version: "3.9"
services:
  matomo:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./nginx-default.conf:/etc/nginx/sites-available/default
    environment:
      - "TZ=Pacific/Auckland"
      - "USER=33"
  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
configs:
  my_config:
    file: ./my_config.txt
  my_other_config:
    external: true
