version: "3.9"
services:
  matomo:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./nginx-default.conf:/etc/nginx/sites-available/default
    environment:
      - "TZ=Pacific/Auckland"
      - "USER=1000"
    command: "bash -c 'cd /var/www/html; composer install; chown -R www-data:www-data /var/www/html; service php7.4-fpm start; service nginx start; while true; do sleep 3600; done'"
  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
configs:
  my_config:
    file: ./my_config.txt
  my_other_config:
    external: true
