name: Merge to Head

on:
  workflow_dispatch:
  pull_request:
    types: [ synchronize ]

permissions:
  actions: read
  checks: none
  contents: write
  deployments: none
  issues: read
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current branch
        uses: actions/checkout@v2
        with:
          lfs: false
          submodules: recursive
      - name: Merge ${{ github.base_ref }} -> ${{ github.head_ref }}
        run:
          git fetch ${{ github.base_ref }}
          git merge ${{ github.base_ref }}

