name: Merge to Head

on:
  workflow_dispatch:
  pull_request:
    types: [ synchronize ]

permissions:
  actions: read
  checks: none
  contents: write
  deployments: none
  issues: read
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current branch
        uses: actions/checkout@v2
        with:
          lfs: false
          submodules: recursive

      - name: Merge ${{ github.base_ref }} -> ${{ github.head_ref }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.base_ref }}
          target_branch: ${{ github.head_ref }}
          github_token: ${{ github.token }}

      - name: commit ${{ github.head_ref }} branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: merge to ${{ github.base_ref }}
          branch: ${{ github.head_ref }}

